### ISSUE TITLE
Suport org.freedesktop.Platform version 18.08

### ISSUE THREAD

**Issue by mildred** [endlessm/electron-flatpak-base-app#8]
When building an electron app with the latest SDK and running the app with the latest platform, runnin electron fails with:

```
Gtk-Message: 00:20:56.817: Failed to load module "canberra-gtk-module"
Gtk-Message: 00:20:56.817: Failed to load module "canberra-gtk-module"
App threw an error during load
Error: /app/lib/libnssutil3.so: version `NSSUTIL_3.38' not found (required by /usr/lib/x86_64-linux-gnu/libssl3.so)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/main/node_modules/nodegit/dist/nodegit.js:12:12)
    at Object.<anonymous> (/app/main/node_modules/nodegit/dist/nodegit.js:1145:3)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /app/lib/libnssutil3.so: version `NSSUTIL_3.38' not found (required by /usr/lib/x86_64-linux-gnu/libssl3.so)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/main/node_modules/nodegit/dist/nodegit.js:12:12)
    at Object.<anonymous> (/app/main/node_modules/nodegit/dist/nodegit.js:1145:3)
```

The electron base app needs to be rebuilt with the latest platform.

**Comment by ptomato** [comment]
The electron base app itself is now provided by Flathub (https://github.com/flathub/io.atom.electron.BaseApp), so I would recommend using that one instead.
